#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "client.h"

// array for convert msg_id (= index in array) to appropriate event
/*event events[] = {EV_LOGIN, EV_ROOMS, EV_FIND, EV_CREATE, EV_JOIN, EV_LOGOUT, EV_LEAVE, EV_TURN, EV_TAKE_STONE, EV_OPP_CON_OK, EV_OPP_TURN_REPLY,
    EV_OPP_TAKE_STONE_REPLY, EV_OPP_LEAVE_OK, EV_OPP_LOST_CON_OK, EV_OPP_RECON_OK, EV_OPP_DISCON_OK, EV_UPDATE_ROOM_OK, EV_PING_OK
 };*/

state transitions[STATES_COUNT][EVENTS_COUNT] = {
  [ST_CONNECTED][EV_LOGIN] = ST_LOBBY,
  [ST_CONNECTED][EV_ROOMS] = ST_INVALID,
  [ST_CONNECTED][EV_FIND] = ST_INVALID,
  [ST_CONNECTED][EV_CREATE] = ST_INVALID,
  [ST_CONNECTED][EV_JOIN] = ST_INVALID,
  [ST_CONNECTED][EV_LOGOUT] = ST_INVALID,
  [ST_CONNECTED][EV_LEAVE] = ST_INVALID,
  [ST_CONNECTED][EV_TURN] = ST_INVALID,
  [ST_CONNECTED][EV_TAKE_STONE] = ST_INVALID,
  [ST_CONNECTED][EV_OPP_CON_OK] = ST_INVALID,
  [ST_CONNECTED][EV_OPP_TURN_OK] = ST_INVALID,
  [ST_CONNECTED][EV_OPP_TAKE_STONE_OK] = ST_INVALID,
  [ST_CONNECTED][EV_OPP_LEAVE_OK] = ST_INVALID,
  [ST_CONNECTED][EV_OPP_LOST_CON_OK] = ST_INVALID,
  [ST_CONNECTED][EV_OPP_RECON_OK] = ST_INVALID,
  [ST_CONNECTED][EV_OPP_DISCON_OK] = ST_INVALID,
  [ST_CONNECTED][EV_UPDATE_ROOM_OK] = ST_INVALID,
  [ST_CONNECTED][EV_PING_OK] = ST_CONNECTED,

  [ST_LOBBY][EV_LOGIN] = ST_INVALID,
  [ST_LOBBY][EV_ROOMS] = ST_LOBBY,
  [ST_LOBBY][EV_FIND] = ST_OPP_TURN,
  [ST_LOBBY][EV_CREATE] = ST_WAITING_FOR_OPP,
  [ST_LOBBY][EV_JOIN] = ST_OPP_TURN,
  [ST_LOBBY][EV_LOGOUT] = ST_DISCONNECTED,
  [ST_LOBBY][EV_LEAVE] = ST_INVALID,
  [ST_LOBBY][EV_TURN] = ST_INVALID,
  [ST_LOBBY][EV_TAKE_STONE] = ST_INVALID,
  [ST_LOBBY][EV_OPP_CON_OK] = ST_INVALID,
  [ST_LOBBY][EV_OPP_TURN_OK] = ST_INVALID,
  [ST_LOBBY][EV_OPP_TAKE_STONE_OK] = ST_INVALID,
  [ST_LOBBY][EV_OPP_LEAVE_OK] = ST_INVALID,
  [ST_LOBBY][EV_OPP_LOST_CON_OK] = ST_INVALID,
  [ST_LOBBY][EV_OPP_RECON_OK] = ST_INVALID,
  [ST_LOBBY][EV_OPP_DISCON_OK] = ST_INVALID,
  [ST_LOBBY][EV_UPDATE_ROOM_OK] = ST_LOBBY,
  [ST_LOBBY][EV_PING_OK] = ST_LOBBY,

  [ST_WAITING_FOR_OPP][EV_LOGIN] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_ROOMS] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_FIND] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_CREATE] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_JOIN] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_LOGOUT] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_LEAVE] = ST_LOBBY,
  [ST_WAITING_FOR_OPP][EV_TURN] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_TAKE_STONE] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_OPP_CON_OK] = ST_MY_TURN,
  [ST_WAITING_FOR_OPP][EV_OPP_TURN_OK] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_OPP_TAKE_STONE_OK] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_OPP_LEAVE_OK] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_OPP_LOST_CON_OK] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_OPP_RECON_OK] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_OPP_DISCON_OK] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_UPDATE_ROOM_OK] = ST_INVALID,
  [ST_WAITING_FOR_OPP][EV_PING_OK] = ST_WAITING_FOR_OPP,

  [ST_MY_TURN][EV_LOGIN] = ST_INVALID,
  [ST_MY_TURN][EV_ROOMS] = ST_INVALID,
  [ST_MY_TURN][EV_FIND] = ST_INVALID,
  [ST_MY_TURN][EV_CREATE] = ST_INVALID,
  [ST_MY_TURN][EV_JOIN] = ST_INVALID,
  [ST_MY_TURN][EV_LOGOUT] = ST_INVALID,
  [ST_MY_TURN][EV_LEAVE] = ST_LOBBY,
  [ST_MY_TURN][EV_TURN] = ST_OPP_TURN,
  [ST_MY_TURN][EV_TAKE_STONE] = ST_INVALID,
  [ST_MY_TURN][EV_OPP_CON_OK] = ST_INVALID,
  [ST_MY_TURN][EV_OPP_TURN_OK] = ST_INVALID,
  [ST_MY_TURN][EV_OPP_TAKE_STONE_OK] = ST_INVALID,
  [ST_MY_TURN][EV_OPP_LEAVE_OK] = ST_LOBBY,
  [ST_MY_TURN][EV_OPP_LOST_CON_OK] = ST_OPP_LOST_CON,
  [ST_MY_TURN][EV_OPP_RECON_OK] = ST_INVALID,
  [ST_MY_TURN][EV_OPP_DISCON_OK] = ST_LOBBY,
  [ST_MY_TURN][EV_UPDATE_ROOM_OK] = ST_INVALID,
  [ST_MY_TURN][EV_PING_OK] = ST_MY_TURN,

  [ST_OPP_TURN][EV_LOGIN] = ST_INVALID,
  [ST_OPP_TURN][EV_ROOMS] = ST_INVALID,
  [ST_OPP_TURN][EV_FIND] = ST_INVALID,
  [ST_OPP_TURN][EV_CREATE] = ST_INVALID,
  [ST_OPP_TURN][EV_JOIN] = ST_INVALID,
  [ST_OPP_TURN][EV_LOGOUT] = ST_INVALID,
  [ST_OPP_TURN][EV_LEAVE] = ST_LOBBY,
  [ST_OPP_TURN][EV_TURN] = ST_INVALID,
  [ST_OPP_TURN][EV_TAKE_STONE] = ST_INVALID,
  [ST_OPP_TURN][EV_OPP_CON_OK] = ST_INVALID,
  [ST_OPP_TURN][EV_OPP_TURN_OK] = ST_MY_TURN,
  [ST_OPP_TURN][EV_OPP_TAKE_STONE_OK] = ST_INVALID,
  [ST_OPP_TURN][EV_OPP_LEAVE_OK] = ST_LOBBY,
  [ST_OPP_TURN][EV_OPP_LOST_CON_OK] = ST_OPP_TURN,
  [ST_OPP_TURN][EV_OPP_RECON_OK] = ST_INVALID,
  [ST_OPP_TURN][EV_OPP_DISCON_OK] = ST_LOBBY,
  [ST_OPP_TURN][EV_UPDATE_ROOM_OK] = ST_INVALID,
  [ST_OPP_TURN][EV_PING_OK] = ST_OPP_TURN,

  [ST_TAKING_STONE][EV_LOGIN] = ST_INVALID,
  [ST_TAKING_STONE][EV_ROOMS] = ST_INVALID,
  [ST_TAKING_STONE][EV_FIND] = ST_INVALID,
  [ST_TAKING_STONE][EV_CREATE] = ST_INVALID,
  [ST_TAKING_STONE][EV_JOIN] = ST_INVALID,
  [ST_TAKING_STONE][EV_LOGOUT] = ST_INVALID,
  [ST_TAKING_STONE][EV_LEAVE] = ST_LOBBY,
  [ST_TAKING_STONE][EV_TURN] = ST_INVALID,
  [ST_TAKING_STONE][EV_TAKE_STONE] = ST_OPP_TURN,
  [ST_TAKING_STONE][EV_OPP_CON_OK] = ST_INVALID,
  [ST_TAKING_STONE][EV_OPP_TURN_OK] = ST_INVALID,
  [ST_TAKING_STONE][EV_OPP_TAKE_STONE_OK] = ST_INVALID,
  [ST_TAKING_STONE][EV_OPP_LEAVE_OK] = ST_LOBBY,
  [ST_TAKING_STONE][EV_OPP_LOST_CON_OK] = ST_OPP_LOST_CON,
  [ST_TAKING_STONE][EV_OPP_RECON_OK] = ST_INVALID,
  [ST_TAKING_STONE][EV_OPP_DISCON_OK] = ST_LOBBY,
  [ST_TAKING_STONE][EV_UPDATE_ROOM_OK] = ST_INVALID,
  [ST_TAKING_STONE][EV_PING_OK] = ST_TAKING_STONE,

  [ST_OPP_TAKING_STONE][EV_LOGIN] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_ROOMS] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_FIND] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_CREATE] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_JOIN] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_LOGOUT] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_LEAVE] = ST_LOBBY,
  [ST_OPP_TAKING_STONE][EV_TURN] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_TAKE_STONE] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_OPP_CON_OK] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_OPP_TURN_OK] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_OPP_TAKE_STONE_OK] = ST_MY_TURN,
  [ST_OPP_TAKING_STONE][EV_OPP_LEAVE_OK] = ST_LOBBY,
  [ST_OPP_TAKING_STONE][EV_OPP_LOST_CON_OK] = ST_OPP_TAKING_STONE,
  [ST_OPP_TAKING_STONE][EV_OPP_RECON_OK] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_OPP_DISCON_OK] = ST_LOBBY,
  [ST_OPP_TAKING_STONE][EV_UPDATE_ROOM_OK] = ST_INVALID,
  [ST_OPP_TAKING_STONE][EV_PING_OK] = ST_OPP_TAKING_STONE,

  [ST_OPP_LOST_CON][EV_LOGIN] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_ROOMS] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_FIND] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_CREATE] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_JOIN] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_LOGOUT] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_LEAVE] = ST_LOBBY,
  [ST_OPP_LOST_CON][EV_TURN] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_TAKE_STONE] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_OPP_CON_OK] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_OPP_TURN_OK] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_OPP_TAKE_STONE_OK] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_OPP_LEAVE_OK] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_OPP_LOST_CON_OK] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_OPP_RECON_OK] = ST_UNKNOWN,
  [ST_OPP_LOST_CON][EV_OPP_DISCON_OK] = ST_LOBBY,
  [ST_OPP_LOST_CON][EV_UPDATE_ROOM_OK] = ST_INVALID,
  [ST_OPP_LOST_CON][EV_PING_OK] = ST_OPP_LOST_CON,
};

const char * const state_str[] = {
  [ST_INVALID] = "ST_INVALID",
  [ST_CONNECTED] = "ST_CONNECTED",
  [ST_DISCONNECTED] = "ST_DISCONNECTED",
  [ST_LOBBY] = "ST_LOBBY",
  [ST_WAITING_FOR_OPP] = "ST_WAITING_FOR_OPP",
  [ST_MY_TURN] = "ST_MY_TURN",
  [ST_OPP_TURN] = "ST_OPP_TURN",
  [ST_TAKING_STONE] = "ST_TAKING_STONE",
  [ST_OPP_TAKING_STONE] = "ST_OPP_TAKING_STONE",
  [ST_OPP_LOST_CON] = "ST_OPP_LOST_CON",
  [ST_UNKNOWN] = "ST_UNKNOWN"
};

void print_state(state state) {
    printf("%s (%d)\n", state_str[state], state);
}

int verify_transition(state state, int event_id) {
    return transitions[state][event_id];
}

client *create_client(char *address, int socket, int id) {
    client *new_client;

    if (!address || socket < 0 || id < 0) return NULL;

    new_client = (client *) malloc(sizeof(client));
    if (!new_client) return NULL;

    strncpy(new_client->address, address, strlen(address));
    new_client->socket = socket;
    new_client->id = id;
    new_client->room_number = NOT_IN_ROOM;
    new_client->state = ST_CONNECTED;

    return new_client;
}

void remove_client(client *client) {
    if (client) free(client);
    client = NULL;
}
